gsoc/2017/index.md, gsoc/2017/yohan/post1.md
GSoC 2017 Yohan M R.
Introductory Post
=> Yohan branch

gsoc/2017/index.md, gsoc/2017/mayank/post1.md
Sorry for messing up earlier. Here is the squashed pull request for my first blog post.
* Update post1.md
* Update index.md
=> Mayank's first blog post 

gsoc/2017/index.md
Thanks for the suggestion. Added title.
=> Corrected Title

gsoc/2017/brickbit/post1.md
Sorry for the wait, forget the pull request
=> Attached links to image and to a Gantt

gsoc/2017/index.md, gsoc/2017/mayank/post2.md
Created post2.md and updated index.md with the link
=> Mayank's second blog post

gsoc/2017/aniq/post1.md, gsoc/2017/aniq/post2.md, gsoc/2017/aniq/post3.md, gsoc/2017/aniq/post4.md, gsoc/2017/aniq/post5.md, gsoc/2017/index.md
=> Added Blog posts (Aniq)

gsoc/2017/aniq/post7.md
=> Added blogpost for version 1 of Learnbot-DSL

gsoc/2018/akash_kumar_singh/index.md, gsoc/2018/akash_kumar_singh/post1.md, gsoc/2018/index.md
A brief intro to the project "RoboComp-Gazebo Integration".
=> First Post "Introduction"

gsoc/2018/index.md
I have given the link of the post1.
=> updated link to first post.

gsoc/2018/akash_kumar_singh/post3.md, gsoc/2018/akash_kumar_singh/post4.md, gsoc/2018/index.md
This blog describes about the ways in which one can have access to the gazebo element, in the same as they have with the plugins. It shows how the access is created and passed to the plugins to use.
=> Added 4th blog

gsoc/2018/akash_kumar_singh/post5.md, gsoc/2018/index.md
This post contains the demo video of the integration between `gazebo` and `robocomp` and explains how it works.
=> Added a demo video

gsoc/2018/index.md
@Fahani fixed the `index.md`. Please check now. Thanks.
=> fixed index

gsoc/2018/prinshu_kumar/index.md
Reverts robocomp/web#56
You are making changes in the wrong index
=> Revert "Update index.md"

gsoc/2018/akash_kumar_singh/post5.md, gsoc/2018/akash_kumar_singh/post6.md, gsoc/2018/index.md
The post contains demo  for all the plugins created so far.
=> Added 6th post

gsoc/2018/akash_kumar_singh/post5.md, gsoc/2018/akash_kumar_singh/post6.md, gsoc/2018/akash_kumar_singh/post7.md, gsoc/2018/akash_kumar_singh/post8.md, gsoc/2018/akash_kumar_singh/post9.md, gsoc/2018/index.md
This post describes Slice, specific language for ICE, and how it is used in `robocomp` and `gazebo-robocomp` integration.
=> Added 7th post

gsoc/2018/akash_kumar_singh/post10.md, gsoc/2018/index.md
This is a kind of progress report for the work I have done till now.
=> added 10th post

gsoc/2019/paras_kumar/post01.md
I have created a folder with my name in web/gsoc/2019 and added my first blog post.
=> my first blog

gsoc/2019/mariyam_fedoseeva/post01.md
=> Mfedoseeva intro

gsoc/2019/index.md, gsoc/2019/liubove_orlov_savko/post01.md
Hi, I finally managed to do the pull request. Here is my part. Greetings
=> Liuba, GSoC, first blog entry

gsoc/2020/posts/kanav/post01.md
Introductory Blog for GSoC 2020
=> GSoC 2020 First Post - Kanav

gsoc/2020/posts/shubh_maheshwari/post01.md, gsoc/2020/posts/shubh_maheshwari/post02.md
- First post for updating details about the project 
- Provide updates as of 11th June 2020
=> GSoC 2020 First Pose - Shubh

gsoc/2020/posts/rahul_katiyar/post01.md
=> FirstPost-GUI- Rahul Katiyar

gsoc/2021/posts/fernando_martin/AGM_enviroment.md, gsoc/2021/posts/fernando_martin/Introduction.md, gsoc/2021/posts/index.md
I make a correction of the links and also add format to the posts
=> Correcting links 

gsoc/2021/posts/aditya_kasibhatla/post01.md
Project : https://summerofcode.withgoogle.com/projects/#4930970043547648
=> Create introductory post

gsoc/2021/posts/aditya_kapoor/media/media_files.md, gsoc/2021/posts/aditya_kapoor/post02-crowdnav.md
Corwd Nav environment has been replicated onto webots. This post describes a few details about how are the entities placed in the environment and what they do
=> Environment details

gsoc/2021/posts/fernando_martin/AGGLPlanner_porting(2).md, gsoc/2021/posts/fernando_martin/AGMPlannerPython_component.md, gsoc/2021/posts/fernando_martin/AGMPlanner_component.md, gsoc/2021/posts/fernando_martin/Json_parsing.md, gsoc/2021/posts/index.md
Added all new posts and updated the index to link them
=> Add new Fernando Martin posts

gsoc/2022/posts/index.md, gsoc/2022/posts/sushant_sreeram/1-introduction.md, gsoc/2022/posts/sushant_sreeram/2-environment.md
Added GSoC posts and updated introduction
=> Added Posts 

gsoc/2022/posts/index.md, gsoc/2022/posts/sushant_sreeram/3-agents.md, gsoc/2022/posts/sushant_sreeram/4-additional_features.md
=> Add post 3, 4
